use diffo::{
    diff::{self, DiffSnapshot, DiffSource, Repository},
    store::{MatchStatus, Store},
    util,
};
use serde_json::Value;
use std::{fs, path::PathBuf};

const COMMENTS: &[u8] = include_bytes!("fixtures/zig-v1/comments.json");
const STATES: &[u8] = include_bytes!("fixtures/zig-v1/review-states.json");
const PATCH: &[u8] = include_bytes!("fixtures/zig-v1/working-tree.patch");

fn snapshot() -> DiffSnapshot {
    let identity: Value =
        serde_json::from_str(include_str!("fixtures/zig-v1/identity.json")).unwrap();
    let realpath = identity["repository_realpath"].as_str().unwrap();
    let repo_id = format!("repo_{}", &util::hash_hex(realpath.as_bytes())[..16]);
    assert_eq!(repo_id, identity["repository_id"]);
    let target = diff::make_review_target(&[]);
    assert_eq!(target.target_id, identity["review_target_id"]);
    DiffSnapshot {
        snapshot_id: String::new(),
        repository: Repository {
            root_path: PathBuf::from(realpath),
            repo_id,
            current_branch: "fixture".into(),
        },
        review_target: target,
        files: diff::parse_patch(PATCH, DiffSource::Unstaged).unwrap(),
    }
}

fn legacy_store() -> (tempfile::TempDir, Store) {
    let temp = tempfile::tempdir().unwrap();
    fs::write(temp.path().join("comments.json"), COMMENTS).unwrap();
    fs::write(temp.path().join("review-states.json"), STATES).unwrap();
    let store = Store::at(temp.path()).unwrap();
    (temp, store)
}

#[test]
fn zig_generated_anchors_and_review_identity_remain_exact() {
    // These fixtures were emitted by Zig at 45c1d47, not generated by Rust tests.
    let snapshot = snapshot();
    let (_temp, mut store) = legacy_store();
    store.refresh_match_status(&snapshot);
    let file = &snapshot.files[0];
    assert!(store.is_reviewed(
        &file.path,
        &file.patch_fingerprint,
        &snapshot.review_target.target_id
    ));
    assert_eq!(store.comments.len(), 2);
    for comment in &store.comments {
        assert_eq!(comment.match_status, MatchStatus::Exact);
        assert_eq!(comment.patch_fingerprint, file.patch_fingerprint);
        assert_eq!(comment.repository_id, snapshot.repository.repo_id);
        assert!(file.hunks.iter().flat_map(|h| &h.lines).any(|line| {
            line.stable_line_id == comment.stable_line_id
                && if comment.side == "old" {
                    line.old_lineno == Some(comment.start_line)
                } else {
                    line.new_lineno == Some(comment.start_line)
                }
        }));
    }
}

#[test]
fn zig_documents_survive_rust_save_and_append_without_data_conversion() {
    let snapshot = snapshot();
    let (temp, mut store) = legacy_store();
    store.save().unwrap();
    for (name, original) in [("comments.json", COMMENTS), ("review-states.json", STATES)] {
        let saved: Value =
            serde_json::from_slice(&fs::read(temp.path().join(name)).unwrap()).unwrap();
        assert_eq!(saved, serde_json::from_slice::<Value>(original).unwrap());
    }
    let file = &snapshot.files[0];
    let hunk = &file.hunks[0];
    store
        .add_comment(
            &snapshot.repository.repo_id,
            &snapshot.review_target.target_id,
            file,
            &hunk.lines[0],
            &hunk.header,
            3,
            "Rust comment.",
            "Migration Test",
        )
        .unwrap();
    let saved: Value =
        serde_json::from_slice(&fs::read(temp.path().join("comments.json")).unwrap()).unwrap();
    let original: Value = serde_json::from_slice(COMMENTS).unwrap();
    assert_eq!(
        &saved["comments"].as_array().unwrap()[..2],
        original["comments"].as_array().unwrap()
    );
    let reloaded = Store::at(temp.path()).unwrap();
    assert_eq!(reloaded.comments.len(), 3);
    assert_eq!(reloaded.comments[2].body, "Rust comment.");
}

#[test]
fn only_a_changed_patch_invalidates_zig_review_data() {
    let mut snapshot = snapshot();
    let (_temp, mut store) = legacy_store();
    snapshot.files[0].patch_fingerprint = "sha256:changed".into();
    store.refresh_match_status(&snapshot);
    assert!(
        store
            .comments
            .iter()
            .all(|c| c.match_status == MatchStatus::Stale)
    );
    assert!(!store.is_reviewed(
        &snapshot.files[0].path,
        &snapshot.files[0].patch_fingerprint,
        &snapshot.review_target.target_id
    ));
    snapshot.files.clear();
    store.refresh_match_status(&snapshot);
    assert!(
        store
            .comments
            .iter()
            .all(|c| c.match_status == MatchStatus::Missing)
    );
}
